name = "Minecraft ( Dether Craft )"
author = "Kazilsky"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87386ed588293b28fb111b66fe23829402e5445a071053b1b10a460f1eb4c48b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
