name = "Minecraft ( Dether Craft )"
author = "Kazilsky"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e1dfb9249e1b8258cedfd2ded62805a3cf03ceb8c8157f20a739ff602af0ece"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
