name = "Minecraft ( Dether Craft )"
author = "Kazilsky"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e733817a845c200a69933eef5e8142c52b76a7350e3ac79f47f33407b0e8173"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
